# Generated by Django 4.1.4 on 2022-12-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ('nome',), 'verbose_name': 'aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('codigo_curso',), 'verbose_name': 'curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
